metadata:
  name: xreplicatedmaps.simple.cuefn.example.com
spec:
  group: simple.cuefn.example.com
  names:
    plural: xreplicatedmaps
    kind: XReplicatedMap
  claimNames:
    kind: ReplicatedMap
    plural: replicatedmaps
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: A config map that is replicated to multiple namespaces
          type: object
          required:
            - spec
          properties:
            spec:
              description: desired state of the replicated config map
              type: object
              required:
                - parameters
              properties:
                parameters:
                  description: input parameters
                  type: object
                  required:
                    - data
                    - namespaces
                  properties:
                    data:
                      description: data for the config map that will be created
                      type: object
                      additionalProperties:
                        type: string
                    namespaces:
                      description: the namespaces to replicate the config map
                      type: array
                      items:
                        type: string
                    name:
                      description: optional name for the config map. Default is the claim name
                      type: string
kind: CompositeResourceDefinition
apiVersion: apiextensions.crossplane.io/v1
---
metadata:
  name: xs3buckets.simple.cuefn.example.com
spec:
  group: simple.cuefn.example.com
  names:
    plural: xs3buckets
    kind: XS3Bucket
  claimNames:
    kind: S3Bucket
    plural: s3buckets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      additionalPrinterColumns:
        - jsonPath: .status.APIEndpoint
          name: Endpoint
          type: string
        - jsonPath: .spec.resourceRef.name
          name: external-name
          type: string
      schema:
        openAPIV3Schema:
          description: allow creation of one of more S3 buckets
          type: object
          required:
            - spec
          properties:
            spec:
              description: desired state
              type: object
              required:
                - parameters
              properties:
                parameters:
                  description: bucket creation parameters
                  type: object
                  required:
                    - region
                  properties:
                    region:
                      description: bucket region
                      type: string
                    additionalSuffixes:
                      description: additional buckets to create with the suffixes provided
                      type: array
                      items:
                        type: string
                        minLength: 1
                        maxLength: 4
                    tags:
                      description: tags to associate with all buckets
                      type: object
                      additionalProperties:
                        type: string
            status:
              description: observed status
              type: object
              properties:
                primaryEndpoint:
                  description: the URL of the bucket endpoint
                  type: string
                additionalEndpoints:
                  description: additional endpoints in the same order as additional suffixes
                  type: array
                  items:
                    type: string
                iamPolicyARN:
                  description: the ARN of the IAM policy created for accessing the buckets
                  type: string
kind: CompositeResourceDefinition
apiVersion: apiextensions.crossplane.io/v1

---
