# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - exportloopref
    - forcetypeassert
    - gci
    - gocritic
    - godot
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - stylecheck
    - tenv
    - unconvert
    - unparam
    - unused
    - vet

run:
  timeout: 10m
