name: check license headers
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check-gen:
    name: check license headers
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - id: go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache: false
      - name: checks
        run: |
          ./scripts/check/check-license-header.sh
