name: check notices
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check-gen:
    name: check notices
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - id: go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: checks
        run: |
          ./scripts/licenses/generate-notice.sh
          make ci-check-dirty
