name: docker build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  docker-build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: setup
        run: |
          LDFLAGS="$(make ci-print-ldflags)"
          echo "LDFLAGS=${LDFLAGS}">>$GITHUB_ENV
      - name: docker build
        uses: docker/build-push-action@v5
        with:
          build-args:
            ldflags=${{ env.LDFLAGS }}
